export const EXPORT_LABELS = {
  en: {
    title: "Scop Operations Report",
    restaurant: "Restaurant",
    period: "Period",
    branch: "Branch filter",
    allBranches: "All branches",
    summary: "Summary",
    avgCompletion: "Avg completion rate",
    avgPassRate: "Avg pass rate",
    totalCompletions: "Total completions",
    totalReadings: "Total readings",
    passedReadings: "Passed readings",
    dailyCompletion: "Daily completion rate",
    dailyPassRate: "Daily food safety pass rate",
    date: "Date",
    completions: "Completions",
    expected: "Expected",
    rate: "Rate",
    total: "Total",
    passed: "Passed",
    byBranch: "By branch",
    branchName: "Branch",
    completionRate: "Completion %",
    passRate: "Pass %",
    readings: "Readings",
  },
  ar: {
    title: "تقرير عمليات سكوب",
    restaurant: "المطعم",
    period: "الفترة",
    branch: "الفرع",
    allBranches: "جميع الفروع",
    summary: "الملخص",
    avgCompletion: "متوسط معدل الإنجاز",
    avgPassRate: "متوسط معدل النجاح",
    totalCompletions: "إجمالي الإنجازات",
    totalReadings: "إجمالي القراءات",
    passedReadings: "قراءات ناجحة",
    dailyCompletion: "معدل الإنجاز اليومي",
    dailyPassRate: "معدل نجاح سلامة الغذاء",
    date: "التاريخ",
    completions: "الإنجازات",
    expected: "المتوقع",
    rate: "النسبة",
    total: "الإجمالي",
    passed: "الناجح",
    byBranch: "حسب الفرع",
    branchName: "الفرع",
    completionRate: "نسبة الإنجاز",
    passRate: "نسبة النجاح",
    readings: "القراءات",
  },
} as const;

export type ExportLocale = keyof typeof EXPORT_LABELS;
